config/routes.rb
Pizzaria::Application.routes.draw do
  resources :order_flavors

  resources :sizes

  resources :flavors

  resources :user_sessions
  resources :users
  
  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'help' => "dashboard#help", :as => :help
  
  match 'recover_password' => "user_sessions#recover_password", :as => :recover_password

  match 'orders/:id' => 'orders#new', :as => :new_order
  match 'show_order/:id' => 'orders#show', :as => :show_order
   match 'order_products' => 'orders#order_products', :as => :order_products
  match 'orders' => 'orders#index', :as => :orders
  match 'finalize_or_cancel/:id/:type' => 'orders#finalize_or_cancel', :as => :finalize_or_cancel_order  
  
  
  match 'delete_itens/:id' => 'order_products#destroy', :as => :delete_itens 

  root :to => 'dashboard#index'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  has_many :order_flavors, :foreign_key => "flavor_id"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_attached_file :icon
  has_many :products
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products
  belongs_to :status
  
   def self.exist_order(user,status)
    where("user_id = '#{user}' AND status_id = '#{status}'").first
  end
  
  def self.total_order
    
  end
end

app/models/order_flavor.rb
class OrderFlavor < ActiveRecord::Base
  
  belongs_to :flavor
  belongs_to :order_product
  
  
  def self.add(order,sabores)
    sabores.each do |s|
      self.create(:flavor_id => s, :order_product_id => order)
    end
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :size
  has_many :order_flavors, :foreign_key => "order_product_id"
  
  
  def self.add_products(order, product, size)
    current_item = OrderProduct.find(:first, :conditions => { :order_id => order.id, :product_id => product })    
    
    if current_item && product != "8"
      qnt = current_item.amount + 1
      current_item.update_attributes(:amount => qnt)
    else
      @order_product = self.new(:order_id => order.id, :product_id => product, :amount => 1, :size_id => size.blank? ? 0 :size)
      @order_product.save
    end
    
  end
  
  def self.total(itens)
    @total = 0
    itens.each do |v|
      if v.product_id == 8
        @total = (@total + v.size.value) * v.amount
      else
        @total = (@total + v.product.price) * v.amount
      end      
    end
    return @total
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base  
   belongs_to :group
   has_many :order_products
   
   attr_accessor :size_id
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_many :order_products
end

app/models/status.rb
class Status < ActiveRecord::Base
  set_table_name "status"

  has_many :orders, :foreign_key => "status_id"
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  validates_presence_of :name, :email, :password
  validates_uniqueness_of :email
  
  acts_as_authentic do |c|
    c.login_field :email
    c.validate_login_field false
  end 
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_email
   
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  def persisted?
    false
   end
   
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "application"
  
  before_filter :logado
  before_filter :load_variables
  
  def index
    @orders = Order.new
    @product = Product.new 
    if @order
      @itens = OrderProduct.where(:order_id => @order.id)
      puts "--------------------------------------#{@itens.inspect}"
    end 
  end
  
  def help
    
  end
  
  
  private
  def load_variables
    @groups = Group.all
    @sizes = Size.all
    @order = Order.first(:conditions => ["status_id = ? AND user_id = ? ", 1, current_user.id]) 
    @flavors = Flavor.all
  end
  
  def logado
    unless current_user
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sizes }
    end
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
    @size = Size.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @size }
    end
  end

  # GET /sizes/new
  # GET /sizes/new.json
  def new
    @size = Size.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @size }
    end
  end

  # GET /sizes/1/edit
  def edit
    @size = Size.find(params[:id])
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(params[:size])

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, :notice => 'Size was successfully created.' }
        format.json { render :json => @size, :status => :created, :location => @size }
      else
        format.html { render :action => "new" }
        format.json { render :json => @size.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sizes/1
  # PUT /sizes/1.json
  def update
    @size = Size.find(params[:id])

    respond_to do |format|
      if @size.update_attributes(params[:size])
        format.html { redirect_to @size, :notice => 'Size was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @size.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size = Size.find(params[:id])
    @size.destroy

    respond_to do |format|
      format.html { redirect_to sizes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js
  
  skip_before_filter :require_user, :only => [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
      if @user.save
        flash[:notice] = "Usuário criado com sucesso."        
      else
        @user.errors
      end
    respond_with @user
  end
  
  def edit
    @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      flash[:notice] = "Cadastro atualizado com sucesso."
    else
      @user.errors
    end
    respond_with @user 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
   def add_itens(product)
    puts "-------------------------------------------------------addd"
  end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_pedido.html.erb
<div class="block-border"><div class="block-content">
				<h1>Itens do pedido</h1>
				
				<ul class="extended-list no-margin icon-user">
					<% if @itens %>
						<% @itens.each do |v| %>
						<li id="<%= dom_id v %>">
							<div>
								<span class="icon"><%= image_tag v.product.photo_file_name, :title => v.product.name, :width =>50 %></span>
								<h3><%= v.product.name %></h3><br>
								<% if v.product_id == 2 %>
									<% v.order_flavors.each do |s|%>
										<%= s.flavor.name.capitalize %>,
									<% end %>
								<% end %>
								
							</div>
							
							<ul class="mini-menu" style="opacity: 0;">
								<li><a title="Edit" href="javascript:void(0)"><img width="16" height="16" src="images/icons/fugue/pencil.png"></a></li>								
								<li><%= link_to "Excluir", delete_itens_path(v.id), :remote => true %></li>
							</ul>
							
							<ul class="extended-options">
								<li>
									Quantidade: <strong><%= v.amount %></strong><br>
									
								</li>
								<li>
									Valor: <strong><% if v.product_id == 8 %><%= (v.size.value * v.amount).contabil %><%else%><%= (v.product.price * v.amount).contabil %><%end%></strong><br>
									
								</li>
							</ul>
						</li>
						
						<% end %>
					<% end %>
				</ul>
				
				<ul class="message no-margin">
					<% if @itens %>
						<li><%= @itens.count %> itens no seu pedido</li>
						<li>Valor total: <h2>R$ <%= OrderProduct.total(@itens).contabil %></h2></li>
					<% end %>
				</ul>
			</div></div>

app/views/dashboard/help.html.erb
<section class="grid_12">
			<div class="block-border"><div class="block-content">
				<!-- We could put the menu inside a H1, but to get valid syntax we'll use a wrapper -->
				<div class="h1 with-menu">
					<h1>Ajuda</h1>					
				</div>
			
					<dl class="accordion">
					<dt><span class="number">1</span> Como fazer seu pedido </dt>
					<dd>
						<p>Ao acessar o sistema, logo podemos ver a tela que lista os produtos.</p>
						<p>Na aba superior onde estão listados as categorias, clique sobre alguma para ver os produtos da mesma.</p>
						<p>Clique em "Adicionar o Produto" para adiciona-lo em seu pedido.</p>
					</dd>
					
					<dt><span class="number">2</span> Listando os pedidos</dt>
					<dd>
						<p>Clique no menu "Meus Pedidos", são listados todos com seu devido status</p>
						<p>Se o status do seu pedido for do tipo "Início", então terá um botão para enviar o pedido para produção.</p>
						<p>Após o pedido ser realizado, terá um tempo de 10 minutos para cancela-lô.</p>
					</dd>
					
					<dt><span class="number">3</span> Editar meu cadastro</dt>
					<dd>
						<p>Clicando no menu "Meu Cadastro" visualizamos um formulário com os dados que podem ser atualizados.</p>
					</dd>
					
					<dt><span class="number">4</span> Visualizar itens do pedido</dt>
					<dd>
						<p>Na listagem de pedidos temos o botão "Detalhes", após clicado apresentará do lado direito os detalhes do pedido.</p>
					</dd>
					
					<dt><span class="number">5</span> Excluir itens do pedido aberto</dt>
					<dd>
						<p>Na listagem de produtos, no lado direito apresentará o pedido aberto. Passando o mouse sobre os itens do pedido temos a opção excluir.</p>
					</dd>
				</dl>
				
				<ul class="message no-margin">
					<li>Se sua dúvida não foi resolvida, ligue para nosso suporte técnico,<strong>(66) 9656-3337</strong>.</li>
				</ul>
				
			</div></div>
		</section>

app/views/dashboard/index.html.erb
<section class="grid_8">
			<div class="block-border"><div class="block-content">
				<!-- We could put the menu inside a H1, but to get valid syntax we'll use a wrapper -->
				<div class="h1 with-menu">
					<h1>Produtos</h1>					
				</div>
			
				<div class="block-controls">
					
					<ul class="controls-tabs js-tabs same-height with-children-tip">
						<% @groups.each do |g| %>
							<li class="" title="<%= g.name %>"><a href="#<%= g.name.downcase %>" title="<%= g.name %>"><%= image_tag g.icon_file_name, :title => g.name, :width => 24, :height => 24 %></a></li>
						<% end %>
					</ul>
					
				</div>
				<% @groups.each do |g| %>
					<% if g.id == 2 %>
						<div style=" display: inline-block;" id="<%= g.name.downcase %>" class="with-margin">
						<h2><%= g.name %></h2>
						<ul class="">
						<% g.products.each do |p| %>
						<%= form_for [@orders, @product] do |r| %>
							<li class="product pizza">
								<%= image_tag p.photo_file_name, :title => p.name, :width => 100 %>
								
								<p class="name_product"><%= p.name %></p>
								<%= select :product, :size_id, @sizes.collect {|size| [ "#{size.name} - R$ #{size.value.contabil}", size.id ] } %>
								<div class="flavors">
									<% @flavors.each do |f| %>
										<%= check_box_tag 'product[flavor_id][]', f.id %>										
										<%= f.name %> - <em><%= f.additional.contabil if f.additional %></em><br />
										
									<% end %>	
								</div>
								<%= hidden_field_tag "product[product_id]", p.id %>
								<span class="buttons">	
									<%= r.submit "Adicionar ao pedido", :class => "big-button"%>								
									
								</span>	
							</li>	
							<% end %>
						<% end %>
						</ul> 
					</div>
					<%else%>
					<div style=" display: inline-block;" id="<%= g.name.downcase %>" class="with-margin">
						<h2><%= g.name %></h2>
						<ul class="">
						<% g.products.each do |p| %>
							<li class="product">
								<%= image_tag p.photo_file_name, :title => p.name, :width => 100 %>
								<p class="price">R$ <%= p.price.contabil %></p>
								<p class="name_product"><%= p.name %></p>
								<p class="description<%= p.id%>" style="display: none; float: left; margin-top: 10px;"><%= p.description %></p>
								<span class="buttons">
									<%= button_tag "" "Detalhes", :class => "show_description", :id => "description#{p.id}" %>
									<%= link_to "Adicionar ao pedido", new_order_path(p.id), :class => "big-button" %>
								</span>	
							</li>	
						<% end %>
						</ul> 
					</div>
					<%end%>
				<% end %>
				<div style="height: 435px; display: none;" id="outros" class="with-margin">
					<p>Outros</p>
				</div>		
				
				
				<ul class="message no-margin">
					<li>Faça seu pedido,<strong>é muito fácil</strong>, escolha os produtos.</li>
				</ul>
				
			</div></div>
		</section>
		<section class="grid_4">
			<%= render "pedido" %>
		</section>