config/routes.rb
Pizzaria::Application.routes.draw do
  resources :order_flavors

  resources :sizes

  resources :flavors

  resources :user_sessions
  resources :users
  
  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'help' => "dashboard#help", :as => :help
  
  match 'recover_password' => "user_sessions#recover_password", :as => :recover_password

  match 'orders/:id' => 'orders#new', :as => :new_order
  match 'show_order/:id' => 'orders#show', :as => :show_order
   match 'order_products' => 'orders#order_products', :as => :order_products
  match 'orders' => 'orders#index', :as => :orders
  match 'finalize_or_cancel/:id/:type' => 'orders#finalize_or_cancel', :as => :finalize_or_cancel_order  
  
  
  match 'delete_itens/:id' => 'order_products#destroy', :as => :delete_itens 

  root :to => 'dashboard#index'

end

app/models/order_flavor.rb
class OrderFlavor < ActiveRecord::Base
  
  belongs_to :flavor
  belongs_to :order_product
  
  
  def self.add(order,sabores)
    sabores.each do |s|
      self.create(:flavor_id => s, :order_product_id => order)
    end
  end
end

app/controllers/order_flavors_controller.rb
class OrderFlavorsController < ApplicationController
  # GET /order_flavors
  # GET /order_flavors.json
  def index
    @order_flavors = OrderFlavor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @order_flavors }
    end
  end

  # GET /order_flavors/1
  # GET /order_flavors/1.json
  def show
    @order_flavor = OrderFlavor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order_flavor }
    end
  end

  # GET /order_flavors/new
  # GET /order_flavors/new.json
  def new
    @order_flavor = OrderFlavor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @order_flavor }
    end
  end

  # GET /order_flavors/1/edit
  def edit
    @order_flavor = OrderFlavor.find(params[:id])
  end

  # POST /order_flavors
  # POST /order_flavors.json
  def create
    @order_flavor = OrderFlavor.new(params[:order_flavor])

    respond_to do |format|
      if @order_flavor.save
        format.html { redirect_to @order_flavor, :notice => 'Order flavor was successfully created.' }
        format.json { render :json => @order_flavor, :status => :created, :location => @order_flavor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @order_flavor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_flavors/1
  # PUT /order_flavors/1.json
  def update
    @order_flavor = OrderFlavor.find(params[:id])

    respond_to do |format|
      if @order_flavor.update_attributes(params[:order_flavor])
        format.html { redirect_to @order_flavor, :notice => 'Order flavor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @order_flavor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_flavors/1
  # DELETE /order_flavors/1.json
  def destroy
    @order_flavor = OrderFlavor.find(params[:id])
    @order_flavor.destroy

    respond_to do |format|
      format.html { redirect_to order_flavors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/order_flavors_helper.rb
module OrderFlavorsHelper
end

app/views/order_flavors/_form.html.erb
<%= form_for(@order_flavor) do |f| %>
  <% if @order_flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_flavor.errors.count, "error") %> prohibited this order_flavor from being saved:</h2>

      <ul>
      <% @order_flavor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flavor_id %><br />
    <%= f.number_field :flavor_id %>
  </div>
  <div class="field">
    <%= f.label :order_product_id %><br />
    <%= f.number_field :order_product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_flavors/edit.html.erb
<h1>Editing order_flavor</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_flavor %> |
<%= link_to 'Back', order_flavors_path %>

app/views/order_flavors/index.html.erb
<h1>Listing order_flavors</h1>

<table>
  <tr>
    <th>Flavor</th>
    <th>Order product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_flavors.each do |order_flavor| %>
  <tr>
    <td><%= order_flavor.flavor_id %></td>
    <td><%= order_flavor.order_product_id %></td>
    <td><%= link_to 'Show', order_flavor %></td>
    <td><%= link_to 'Edit', edit_order_flavor_path(order_flavor) %></td>
    <td><%= link_to 'Destroy', order_flavor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order flavor', new_order_flavor_path %>

app/views/order_flavors/new.html.erb
<h1>New order_flavor</h1>

<%= render 'form' %>

<%= link_to 'Back', order_flavors_path %>

app/views/order_flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Flavor:</b>
  <%= @order_flavor.flavor_id %>
</p>

<p>
  <b>Order product:</b>
  <%= @order_flavor.order_product_id %>
</p>


<%= link_to 'Edit', edit_order_flavor_path(@order_flavor) %> |
<%= link_to 'Back', order_flavors_path %>