config/routes.rb
Pizzaria::Application.routes.draw do
  resources :order_flavors

  resources :sizes

  resources :flavors

  resources :user_sessions
  resources :users
  
  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'help' => "dashboard#help", :as => :help
  
  match 'recover_password' => "user_sessions#recover_password", :as => :recover_password

  match 'orders/:id' => 'orders#new', :as => :new_order
  match 'show_order/:id' => 'orders#show', :as => :show_order
   match 'order_products' => 'orders#order_products', :as => :order_products
  match 'orders' => 'orders#index', :as => :orders
  match 'finalize_or_cancel/:id/:type' => 'orders#finalize_or_cancel', :as => :finalize_or_cancel_order  
  
  
  match 'delete_itens/:id' => 'order_products#destroy', :as => :delete_itens 

  root :to => 'dashboard#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products
  belongs_to :status
  
   def self.exist_order(user,status)
    where("user_id = '#{user}' AND status_id = '#{status}'").first
  end
  
  def self.total_order
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :html, :js
  
  def new
 
      @order = Order.new
      @order.user_id = current_user.id
      @order.status_id = 1
      
      size= params[:size].blank? ? 0 : params[:size]
      
      product = params[:id]
      
      @orders = Order.exist_order(current_user.id, 1)
      
      if @orders
        OrderProduct.add_products(@orders,product, size)
        flash[:notice] = "Seu produto foi adicionado em pedido existente"
        redirect_to root_path
      else
          @order.save
          OrderProduct.add_products(@order,product, size)
          flash[:notice] = "Produto adicionado"
          redirect_to root_path
      end

  end
  
  def create
    @order = Order.new(user)
    @order.user_id = user
    if @order.save
      puts "----------------"
    end
  end
  
  def index
    @orders = Order.where(:user_id => current_user.id)
  end
  
  def finalize_or_cancel
    id = params[:id]
    action = params[:type]
    
    @order = Order.first(:conditions => {:id => id})
    if @order.update_attributes(:status_id => action)
      if action == "5"
        flash[:notice] = "Pedido cancelado com sucesso."
      else
        flash[:notice] = "Pedido enviado para produção com sucesso, aguarde a entrega."
      end
      
    end
    respond_with @order
  end
  
  def show
    order = params[:id]
    @order = Order.find_by_id(order)
    @itens = OrderProduct.where(:order_id => @order.id)
  end
  
  def order_products
    if params[:product]
      @order = Order.new
      @order.user_id = current_user.id
      @order.status_id = 1
      product = params[:product][:product_id]
      size = params[:product][:size_id]
      
      @orders = Order.exist_order(current_user.id, 1)
      
      if @orders
        
        OrderProduct.add_products(@orders,product, size)
        
        
        OrderFlavor.add(OrderProduct.last.id, params[:product][:flavor_id])
        flash[:notice] = "Seu produto foi adicionado em pedido existente"
        redirect_to root_path
      else
          @order.save
          OrderProduct.add_products(@order,product)
          flash[:notice] = "Produto adicionado"
          redirect_to root_path
      end
    end
  end
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_itens.html.erb
<div class="block-border"><div class="block-content">
				<h1>Itens do pedido</h1>
				
				<ul class="extended-list no-margin icon-user">
					<% if @itens %>
						<% @itens.each do |v| %>
						<li id="<%= dom_id v %>">
							<div>
								<span class="icon"><%= image_tag v.product.photo_file_name, :title => v.product.name, :width =>50 %></span>
								<h3><%= v.product.name %></h3><br>
								<% if v.product_id == 8 %>
									<% v.order_flavors.each do |s|%>
										<%= s.flavor.name.capitalize %>,
									<% end %>
								<% end %>
								
							</div>
							
							
							<ul class="extended-options">
								<li>
									Quantidade: <strong><%= v.amount %></strong><br>
									
								</li>
								<li>
									Valor: <strong><% if v.product_id == 8 %><%= (v.size.value * v.amount).contabil %><%else%><%= (v.product.price * v.amount).contabil %><%end%></strong><br>
									
								</li>
							</ul>
						</li>
						
						<% end %>
					<% end %>
				</ul>
				
				<ul class="message no-margin">
					<% if @itens %>
						<li><%= @itens.count %> itens no seu pedido</li>
						<li>Valor total: <h2>R$ <%= OrderProduct.total(@itens).contabil %></h2></li>
					<% end %>
				</ul>
			</div></div>

app/views/orders/finalize_or_cancel.js.erb
$('#<%= dom_id @order %>').find("#finalize_order").fadeOut();
$(".success").find("li").html("Pedido enviado para produção");
$(".success").fadeIn();

app/views/orders/index.html.erb
<ul class="message warning no-margin" style="display: none;">
	<li></li>
</ul>
<ul class="message success no-margin" style="display: none;">
	<li></li>
</ul>
<section class="grid_8">
			<div class="block-border"><form action="" method="post" id="table_form" class="block-content form">
				
				<h1>Meus Pedidos</h1>
				
				<div class="block-controls">
					
					<ul class="controls-buttons">
						
					</ul>
					
				</div>
			
				<div class="no-margin"><table width="100%" cellspacing="0" class="table">
				
					<thead>
						<tr>
							
							<th scope="col">Status</th>
							<th>Valor</th>
							
							<th scope="col">
								
								Data do pedido
							</th>
							
							<th class="table-actions" scope="col">Ações</th>
						</tr>
					</thead>
					
					<tbody>
						<% @orders.each do |v| %>
						<tr id="<%= dom_id v %>">		
							
							<td><%= v.status.name %></td>
							<td>
								R$ <%= v.order_products.total(v.order_products).contabil %>
									
							</td>
							
							<td><%= v.created_at.strftime("%m de %B de %Y - %H:%M") %></td>
							
							<td class="table-actions">
								<%= link_to "Detalhes", show_order_path(v.id), :remote => true, :id => "cancel_order", :class => "big-button" %>
								
								<% if v.status_id == 1 %>
									<%= link_to "Enviar para produção", finalize_or_cancel_order_path(v.id, 2), :remote => true, :id => "finalize_order", :class => "big-button" %>
								<% end %>
								<% if Time.now < v.created_at + 10.minutes && v.status_id != 4 %>	
									<%= link_to "Cancelar", finalize_or_cancel_order_path(v.id, 5), :remote => true, :id => "cancel_order", :class => "big-button" %>
								<% end %>
							</td>
						</tr>
						
						<% end %>
						
					</tbody>
				
				</table></div>
				
				<ul class="message no-margin">
					<li>Total de Pedidos: <%= @orders.count %></li>
				</ul>
				
				
					
			</form></div>
		</section>
		<section class="grid_4">
			<%= render "itens" %>
		</section>

app/views/orders/new.js.erb
$("#header-shadow").html("<%= flash[:notice] %>");

app/views/orders/show.js.erb
$(".grid_4").html("<%= escape_javascript(render(:partial => "itens")) %>");