config/routes.rb
Pizzaria::Application.routes.draw do
  resources :order_flavors

  resources :sizes

  resources :flavors

  resources :user_sessions
  resources :users
  
  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'help' => "dashboard#help", :as => :help
  
  match 'recover_password' => "user_sessions#recover_password", :as => :recover_password

  match 'orders/:id' => 'orders#new', :as => :new_order
  match 'show_order/:id' => 'orders#show', :as => :show_order
   match 'order_products' => 'orders#order_products', :as => :order_products
  match 'orders' => 'orders#index', :as => :orders
  match 'finalize_or_cancel/:id/:type' => 'orders#finalize_or_cancel', :as => :finalize_or_cancel_order  
  
  
  match 'delete_itens/:id' => 'order_products#destroy', :as => :delete_itens 

  root :to => 'dashboard#index'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  has_many :order_flavors, :foreign_key => "flavor_id"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_attached_file :icon
  has_many :products
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products
  belongs_to :status
  
   def self.exist_order(user,status)
    where("user_id = '#{user}' AND status_id = '#{status}'").first
  end
  
  def self.total_order
    
  end
end

app/models/order_flavor.rb
class OrderFlavor < ActiveRecord::Base
  
  belongs_to :flavor
  belongs_to :order_product
  
  
  def self.add(order,sabores)
    sabores.each do |s|
      self.create(:flavor_id => s, :order_product_id => order)
    end
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :size
  has_many :order_flavors, :foreign_key => "order_product_id"
  
  
  def self.add_products(order, product, size)
    current_item = OrderProduct.find(:first, :conditions => { :order_id => order.id, :product_id => product })    
    
    if current_item && product != "8"
      qnt = current_item.amount + 1
      current_item.update_attributes(:amount => qnt)
    else
      @order_product = self.new(:order_id => order.id, :product_id => product, :amount => 1, :size_id => size.blank? ? 0 :size)
      @order_product.save
    end
    
  end
  
  def self.total(itens)
    @total = 0
    itens.each do |v|
      if v.product_id == 8
        @total = (@total + v.size.value) * v.amount
      else
        @total = (@total + v.product.price) * v.amount
      end      
    end
    return @total
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base  
   belongs_to :group
   has_many :order_products
   
   attr_accessor :size_id
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_many :order_products
end

app/models/status.rb
class Status < ActiveRecord::Base
  set_table_name "status"

  has_many :orders, :foreign_key => "status_id"
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  validates_presence_of :name, :email, :password
  validates_uniqueness_of :email
  
  acts_as_authentic do |c|
    c.login_field :email
    c.validate_login_field false
  end 
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_email
   
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  def persisted?
    false
   end
   
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sizes }
    end
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
    @size = Size.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @size }
    end
  end

  # GET /sizes/new
  # GET /sizes/new.json
  def new
    @size = Size.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @size }
    end
  end

  # GET /sizes/1/edit
  def edit
    @size = Size.find(params[:id])
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(params[:size])

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, :notice => 'Size was successfully created.' }
        format.json { render :json => @size, :status => :created, :location => @size }
      else
        format.html { render :action => "new" }
        format.json { render :json => @size.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sizes/1
  # PUT /sizes/1.json
  def update
    @size = Size.find(params[:id])

    respond_to do |format|
      if @size.update_attributes(params[:size])
        format.html { redirect_to @size, :notice => 'Size was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @size.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size = Size.find(params[:id])
    @size.destroy

    respond_to do |format|
      format.html { redirect_to sizes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
   def add_itens(product)
    puts "-------------------------------------------------------addd"
  end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html lang="en" class="no-js ie ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie"><![endif]-->
<!--[if (gt IE 8)|!(IE)]><!-->
<html lang="pt-BR"><!--<![endif]-->
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
		<title>Pizzaria on-line</title>
		<meta name="description" content="">
		<meta name="author" content="">
	
		<%= stylesheet_link_tag    "application","dashboard" %>
  		<%= javascript_include_tag "application","dashboard" %>
  		<%= csrf_meta_tags %>
	

		<%= stylesheet_link_tag "style" %>
	
		<!-- Modernizr for support detection, all javascript libs are moved right above </body> for better performance -->
		<%= javascript_include_tag "jquery", "ga", "modernizr", "rails" %>	
	</head>
<body>

	<!-- Header -->
	
	<!-- Server status -->
	<header>
		<div class="container_12">
			<img src="/assets/logo.png" class="logo"/>
			<p id="skin-name"><small>Inovation <br />Tecnologia</small> <strong>1.0</strong></p>
			<div class="server-info">Software: <strong>Pizzaria</strong></div>	
		</div>
	</header>
	<!-- End server status -->

	<!-- Main nav -->
	<nav id="main-nav">
		<ul class="container_12">
			<li class="home current">
				<ul>
					<li><%= link_to "Produtos", "/", :title => "Produtos"%></li>
					<li><%= link_to "Meus pedidos", orders_path, :title => "Meus Pedidos" %></li>
					<li><%= link_to "Meu Cadastro", edit_user_path(current_user), :title => "Meu Cadastro" %></li>
					<li><%= link_to "Ajuda", help_path, :title => "Ajuda" %></li>		
				</ul>
			</li>
		</ul>		
	</nav>
	<!-- End main nav -->
	
	<!-- Sub nav -->
	<div id="sub-nav"><div class="container_12">
		
	
	</div></div>
	<!-- End sub nav -->
	
	<!-- Status bar -->
	<div id="status-bar"><div class="container_12">
	
		<ul id="status-infos">
			<li class="spaced">Logado como: <strong><%= current_user.name %></strong></li>
			<li><%= link_to ("<span class='smaller'>Sair do Sistema</span>").html_safe, logout_path, :method => :delete, :confirm => "Deseja realmente sair?", :class => "button red" %></li>
		</ul>
		
			
	</div></div>
	<!-- End status bar -->
	
	<div id="header-shadow">
		
	</div>
	<!-- End header -->
	
	<div id="cb-place-holder" style="height: 58px; display: none;"></div>
	<!-- End control bar -->
	
	<!-- Content -->
	<article class="container_12">
		
		<%= yield %>
		<div class="clear"></div>
		
		
	</article>
	
	<!-- End content -->
	
	<footer>
		
		<div class="float-right">
			<a href="#top" class="button"><img src="assets/navigation-090.png" height="16" width="16"> Ir para o topo</a>
		</div>
		
	</footer>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html lang="en" class="no-js ie ie7 dark"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie dark"><![endif]-->
<!--[if (gt IE 8)|!(IE)]><!-->
<html class=" dark js hashchange backgroundsize boxshadow cssgradients" lang="en"><!--<![endif]--><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>Pizzaria Peperone</title>
	<meta name="description" content="">
	<meta name="author" content="Geisimar Rech">
	
	<!-- Combined stylesheets load -->

	<%= stylesheet_link_tag "style","user_sessions" %>

	
	<!-- Modernizr for support detection, all javascript libs are moved right above </body> for better performance -->
	<%= javascript_include_tag "jquery", "ga", "modernizr", "rails" %>
	
</head>

<!-- the 'special-page' class is only an identifier for scripts -->
<body class="special-page login-bg dark">
<!-- The template uses conditional comments to add wrappers div for ie8 and ie7 - just add .ie, .ie7 or .ie6 prefix to your css selectors when needed -->
<!--[if lt IE 9]><div class="ie"><![endif]-->
<!--[if lt IE 8]><div class="ie7"><![endif]-->	
	
	
	<!--[if lte IE 8]>
		<%= javascript_include_tag "standard.ie.js" %>
	<![endif]-->
	
	<%= yield %>
	<!-- example login script -->
	<script>
	
		$(document).ready(function()
		{
			$("#password-recovery a").click(function(){
				$("#password-recovery fieldset").toggleClass('collapsed');
			});
			
			$(".message").click(function(){
				$(this).fadeOut();
			});
			
			$(".no_cad").click(function(){
				$("#login-block").toggle();
				$("#cad-block").toggle();
				$(".message").html("");
				$(".message").hide();
			})
			
		});
	
	</script>
	
	

<ul id="notifications"></ul></body></html>

app/views/recover_password/recover_password.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    
    <p>
      <%= @message %>
    </p>
  </body>
</html>